---
# tasks file for roles/osp-instance-delete
# grabs all of the hosts from openstack
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
    register: result

# deletes instances with 'QA' as the deployment name
  - name: Delete instances
    os_server:
      cloud: openstack
      name: "{{ item['name'] }}"
      state: 'absent'
    when: item.metadata.deployment_name == 'QA'
    loop: "{{ result['openstack_servers'] }}"
   
