---
- name: Install haproxy
  package:
    name: haproxy
    state: present

- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Enable Haproxy
  service:
    name: haproxy
    state: started
    enabled: true