---

# tasks file for osp.servers
# - name: add QA app server
#   os_server:
#     cloud: openstack
#     name: app1
#     image: rhel-7.6
#     key_name: ansible_ssh_key
#     flavor: m2.medium
#     security_groups: apps
#     delete_fip: yes
#     wait: no
#     nics:
#       - net-name: int_network
#     meta: "group=app_servers, deployment_name=QA"
#     userdata: |
#       #!/bin/bash 
#       curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
#       yum-config-manager --add-repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo

- name: add dev app server
  os_server:
    cloud: openstack
    name: app
    image: rhel-7.6
    key_name: ansible_ssh_key
    flavor: m2.medium
    security_groups: apps
    delete_fip: yes
    wait: no
    state: "{{ instance_state | default('present') }}"
    nics:
      - net-name: int_network
    meta: "group=apps, deployment_name=QA"
    userdata: |
      #!/bin/bash 
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys

- name: add db server
  os_server:
    cloud: openstack
    name: db
    image: rhel-7.6
    key_name: ansible_ssh_key
    flavor: m2.medium
    security_groups: db
    delete_fip: yes
    wait: no
    state: "{{ instance_state | default('present') }}"
    nics:
      - net-name: int_network
    meta: "group=appdbs, deployment_name=QA"
    userdata: |
      #!/bin/bash 
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys

- name: Add frontend server
  os_server:
    cloud: openstack
    name: frontend
    image: rhel-7.6
    key_name: ansible_ssh_key
    flavor: m2.medium
    security_groups: frontend
    delete_fip: yes
    wait: no
    state: "{{ instance_state | default('present') }}"
    nics:
      - net-name: int_network
    meta: "group=frontends, deployment_name=QA"
    userdata: |
      #!/bin/bash 
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys

- name: add floating IP to QA app server
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: app
    network: ext_network
    wait: true
    timeout: 200

- name: add floating IP to QA db server
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: db
    network: ext_network
    wait: true
    timeout: 200

- name: add floating IP to QA frontend server
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: frontend
    network: ext_network
    wait: true
    timeout: 200
