---
#This loop adds all of the servers from the vars file to OSP
- name: add development servers
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    key_name: "{{ item.key_name }}"
    flavor: "{{ item.flavor }}"
    security_groups: "{{ item.security_group }}"
    delete_fip: yes
    wait: no
    #state: "{{ instance_state | default('present') }}"
    nics: "{{ item.nics }}"
    meta: "{{ item.meta }}"
    userdata: "{{ item.userdata }}"
  loop: "{{ osp_servers }}"

# This loop adds a floating IP to all of the development servers
- name: add external floating IP to development server
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item.name }}"
    network: ext_network
    wait: true
    timeout: 200
  loop: "{{ osp_servers }}"
    