---

# tasks file for osp.servers
# - name: add QA app server
#   os_server:
#     cloud: openstack
#     name: app1
#     image: rhel-7.6
#     key_name: ansible_ssh_key
#     flavor: m2.medium
#     security_groups: apps
#     delete_fip: yes
#     wait: no
#     nics:
#       - net-name: int_network
#     meta: "group=app_servers, deployment_name=QA"
#     userdata: |
#       #!/bin/bash 
#       curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
#       yum-config-manager --add-repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo

# This loop adds all of the servers from the vars file to OSP
- name: add development servers
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    key_name: "{{ item.key_name }}"
    flavor: "{{ item.flavor }}"
    security_groups: "{{ item.security_groups }}"
    state: "{{ instance_state | default('present') }}"
    nics: "{{ item.nics }}"
    meta: "{{ item.meta }}"
    userdata: "{{ item.userdata }}"
  loop: {{ osp_servers }}

# - name: add dev app server
#   os_server:
#     cloud: openstack
#     name: app
#     image: rhel-7.6
#     key_name: ansible_ssh_key
#     flavor: m2.medium
#     security_groups: apps
#     delete_fip: yes
#     wait: no
#     state: "{{ instance_state | default('present') }}"
#     nics:
#       - net-name: int_network
#     meta: "group=apps, deployment_name=QA"
#     userdata: |
#       #!/bin/bash 
#       curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
#       cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys

# This loop adds a floating IP to all of the development servers
- name: add external floating IP to development server
  os_floating_ip:
    cloud: openstack
    state: present
    reuse: yes
    server: "{{ item.name }}"
    network: ext_network
    wait: true
    timeout: 200
  loop: "{{ osp_servers }}"
    

# - name: add floating IP to QA app server
#   os_floating_ip:
#     cloud: openstack
#     state: present
#     reuse: yes
#     server: app
#     network: ext_network
#     wait: true
#     timeout: 200

