---
#Need to install Java for Tomcat to fonction properly
- name: Install Java
  yum:
    name: java-1.8.0-openjdk-devel
    state: latest

- name: Install {{ payload }}
  yum:
    name: "{{ payload }}"
    state: latest

- name: Create yum.repo.d directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: Copy web file to tomcat directory
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
  notify: restart {{ payload }}

- name: Enable {{ payload }}
  service:
    name: "{{ payload }}"
    state: started
    enabled: true