---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

#Ensures the repo directory is there
- name: Create yum.repo.d directory
  file:
    path: /etc/yum.repos.d
    state: directory

#Copies the repos from the template to the host
- name: Enable repos from template
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/internal.repo
    owner: root
    group: root
    mode: '0644'
    
#Wasn't sure any base tools needed to be installed but I like vim
- name: install base tools and packages
  yum:
    name: 'vim'
    state: latest