---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: Create yum.repo.d directory
  file:
    path: /etc/yum.repos.d
    state: directory

- name: enable repos
  # I did it this way since these dont seem to have internet access
  # Download this to the working directory http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
  ansible.builtin.copy:
    src: internal.repo
    dest: /etc/yum.repos.d/internal.repo
    owner: root
    group: root
    mode: '0644'
    backup: no
    
- name: install base tools and packages
  yum:
    name: 'vim'
    state: 'latest'

